### ISSUE TITLE
freetype 2.11.0 produces crash when built with MSVC compilers

### ISSUE THREAD

**Issue by Masaiki** [ShiftMediaProject/freetype2#1]
## Context
I'm using libass which links freetype 2.11.0 (subtext and assrender--vapoursynth plugin, xysubfilter with libass--directshow filter for rendering subtitles). And a crash caused by a null pointer dereference occurs when trying to create glyphs with autofit. Both with vcpkg and this repo. I temporarily downgrade to 2.10.4 to solve it. And here is the issue with the same problem in vcpkg https://github.com/microsoft/vcpkg/issues/20246
patch to this problem is also stated in the issue.

## Expected Behavior
no crash

## Actual Behavior
crash casued by null pointer.

## Steps to Reproduce
see the vcpkg issue

## Your Environment

* Version Used:
* Operating System and Version: win10 20h2
* Compiler and Version(s): Visual Studio 16 2019 (MSVC14.29.30133)

## Possible Fix
see the vcpkg issue

**Comment by Sibras** [comment]
Thanks,
I added a patch similar to what you suggested in the vcpkg issue and then have rebuilt the releases.
